apiVersion: apps/v1
kind: Deployment
metadata: 
  name: meuapp-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: meuapp
  template: 
    metadata:
      labels:
        app: meuapp
    spec: 
      containers:
        - name: meuapp
          image: julianorib/meuapp:v1.8
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
